### ISSUE TITLE
[Question] WarpOS Version

### ISSUE THREAD

**Issue by TechTastic** [IpsumCapra/OpenComputersScripts#3]
Hi, thank you for this fix as this problem is super annoying for everyone using OC and WarpDrive

However, before I implement it, will this code work for OpenComputers in MC 1.7.10? Just thought I'd ask before potentially being disappointed if the code only works for MC 1.12 OpenComputers

**Comment by IpsumCapra** [comment]
WarpOS only supports the 1.12.2 version of the WarpDrive mod. See #1.

**Comment by TechTastic** [comment]
Ah well dang. Thanks anyways! I plan to use this alot more when I'm playing a 1.12 modpack again

**Comment by IpsumCapra** [comment]
Glad to hear it. Until then, good luck!
